version: "3.9"

services:
  yaumilpg-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    networks:
      - yaumi_shared
      - default
    restart: always

networks:
  default:
  yaumi_shared:
    external: true